In [1]:
data_files = ["../datasets/mnli/multinli_1.0_dev_matched.jsonl.small.jsonl",
             "../datasets/mnli/multinli_1.0_dev_mismatched.jsonl.small.jsonl",
             ]

In [2]:
import pandas as pd

def load(datasets):
    result = []
    for l in  datasets:
        df = pd.read_json(l, lines=True)
        df["dataset"] = l.split("/")[-1]
        result.append(df)

    return pd.concat(result)

df= load(data_files)
df.sample(n=5)

,gold_label,annotator_labels,pairID,promptID,dataset
1517,entailment,"[entailment, entailment, entailment, entailmen...",56248e,56248,multinli_1.0_dev_matched.jsonl.small.jsonl
8641,contradiction,"[contradiction, contradiction, contradiction, ...",38930c,38930,multinli_1.0_dev_mismatched.jsonl.small.jsonl
3643,neutral,"[neutral, neutral, neutral, neutral, neutral]",8562n,8562,multinli_1.0_dev_mismatched.jsonl.small.jsonl
1117,entailment,"[entailment, entailment, entailment, entailmen...",138448e,138448,multinli_1.0_dev_matched.jsonl.small.jsonl
7769,contradiction,"[contradiction, contradiction, contradiction, ...",2367c,2367,multinli_1.0_dev_matched.jsonl.small.jsonl

In [3]:
df.describe()

            promptID
count   20000.000000
mean    73259.881500
std     42218.092195
min        14.000000
25%     36751.750000
50%     72904.000000
75%    110036.000000
max    146129.000000

In [4]:
from collections import Counter
import random
def add_column_pd(df):
    df["pd"] = df["annotator_labels"].apply(lambda x: Counter(x).most_common()[0][1]/len(x))
    df["majority_label"]= df["annotator_labels"].apply(lambda x: Counter(x).most_common()[0][0])
    return df

def add_column_anotherhuman(df, num_iterations=5):
    for i in range(num_iterations):
        df[f"another_human_{i}"] = df["annotator_labels"].apply(lambda x: random.sample(x, 1)[0])
    return df

In [5]:
df = df.pipe(add_column_pd)\
        .pipe(add_column_anotherhuman)
df.head()

,gold_label,annotator_labels,pairID,promptID,dataset,pd,majority_label,another_human_0,another_human_1,another_human_2,another_human_3,another_human_4
0,neutral,"[neutral, entailment, neutral, neutral, neutral]",63735n,63735,multinli_1.0_dev_matched.jsonl.small.jsonl,0.8,neutral,neutral,neutral,entailment,entailment,neutral
1,contradiction,"[contradiction, contradiction, contradiction, ...",91383c,91383,multinli_1.0_dev_matched.jsonl.small.jsonl,1.0,contradiction,contradiction,contradiction,contradiction,contradiction,contradiction
2,entailment,"[entailment, entailment, entailment, entailmen...",755e,755,multinli_1.0_dev_matched.jsonl.small.jsonl,1.0,entailment,entailment,entailment,entailment,entailment,entailment
3,contradiction,"[contradiction, contradiction, contradiction, ...",78013c,78013,multinli_1.0_dev_matched.jsonl.small.jsonl,1.0,contradiction,contradiction,contradiction,contradiction,contradiction,contradiction
4,contradiction,"[contradiction, contradiction, contradiction, ...",96377c,96377,multinli_1.0_dev_matched.jsonl.small.jsonl,1.0,contradiction,contradiction,contradiction,contradiction,contradiction,contradiction

In [6]:
df["pd"].value_counts()

pd
1.0    11743
0.8     4859
0.6     3045
0.4      353
Name: count, dtype: int64

In [7]:
from sklearn.metrics import accuracy_score
import statistics


def accuracy_by_pd(df,pred_labels, majority_label="majority_label"):
    items_dataset = df["dataset"].unique()
    result   = []
    # For each dataset
    for d in items_dataset:
        df_dataset = df[df["dataset"] == d]
        items_pd = df_dataset["pd"].unique()
        # For pd
        for p_d in items_pd:
            subset_df = df_dataset[df_dataset["pd"] == p_d]
            scores = []

            # For pred label
            for pred_label in pred_labels:
                score = accuracy_score(subset_df[majority_label], subset_df[pred_label])
                scores.append(score)

            result.append({
                "dataset": d,
                "pd": p_d,
                "S": len(subset_df),
                "Expected_Accuracy": p_d,
                 f"score_mean_{pred_labels[0]}": statistics.mean(scores),
                f"score_std_{pred_labels[0]}": statistics.stdev(scores),
                f"delta_expected_{pred_labels[0]}": p_d - statistics.mean(scores),
                "M": "-"

            })
    return pd.DataFrame(result)

scores_df = accuracy_by_pd(df,[l for l in list(df.columns) if l.startswith( "another_human" )])
scores_df

,dataset,pd,S,Expected_Accuracy,score_mean_another_human_0,score_std_another_human_0,delta_expected_another_human_0,M
0,multinli_1.0_dev_matched.jsonl.small.jsonl,0.8,2457,0.8,0.800814,0.008249,-0.000814,-
1,multinli_1.0_dev_matched.jsonl.small.jsonl,1.0,5759,1.0,1.000000,0.000000,0.000000,-
2,multinli_1.0_dev_matched.jsonl.small.jsonl,0.6,1599,0.6,0.589994,0.013026,0.010006,-
3,multinli_1.0_dev_matched.jsonl.small.jsonl,0.4,185,0.4,0.395676,0.060119,0.004324,-
4,multinli_1.0_dev_mismatched.jsonl.small.jsonl,1.0,5984,1.0,1.000000,0.000000,0.000000,-
5,multinli_1.0_dev_mismatched.jsonl.small.jsonl,0.6,1446,0.6,0.602905,0.013476,-0.002905,-
6,multinli_1.0_dev_mismatched.jsonl.small.jsonl,0.8,2402,0.8,0.805828,0.016508,-0.005828,-
7,multinli_1.0_dev_mismatched.jsonl.small.jsonl,0.4,168,0.4,0.390476,0.026150,0.009524,-

In [8]:
def format_latex(df):
    existing_results = {
        "multinli_1.0_dev_matched.jsonl.small.jsonl":{
            1.0: 0.89,
            0.8:  0.78,
            0.60: 0.61

        },
        "multinli_1.0_dev_mismatched.jsonl.small.jsonl":{
            1.0: 0.90,
            0.8:  0.77,
            0.60: 0.62

        }
    }
    dataset_name_dict = {
        "multinli_1.0_dev_matched.jsonl.small.jsonl": "MNLI M  $\\langle$ GT = 5, L=3 $\\rangle$",
        "multinli_1.0_dev_mismatched.jsonl.small.jsonl": "MNLI MM $\\langle$ GT = 5, L=3 $\\rangle$"
    }
    df["formatted_score"] = df.apply(lambda x: f"{x['score_mean_another_human_0']:.2f}$\\pm${x['score_std_another_human_0']:.2f}", axis=1)

    df["formatted_pd"] = df["pd"].apply(lambda x: f"{x:.2f}")
    df["formatted_expected_accuracy"] = df["Expected_Accuracy"].apply(lambda x: f"{x:.2f}")
    df["formatted_dataset"] = df["dataset"].apply(lambda x: f"{dataset_name_dict[x]}")
    df["M"] = df.apply(lambda x: existing_results.get(x['dataset'], {}).get(round(x['pd'],1), None), axis=1)
    df["delta_expected_model"] = df.apply(lambda x: x['Expected_Accuracy'] - x['M'], axis=1)
    df["formated_M"]  =  df["M"] .apply(lambda x: f"{x:.2f}")
    df_new = df.set_index(["formatted_dataset", "formatted_pd", "S"])
    df_new = df_new.sort_values(by=[ "formatted_dataset","pd"])


    return df_new[["formatted_expected_accuracy", "formatted_score", "delta_expected_another_human_0", "formated_M", "delta_expected_model"]].to_latex(index=True)

print(format_latex(scores_df))

\begin{tabular}{lllllrlr}
\toprule
 &  &  & formatted_expected_accuracy & formatted_score & delta_expected_another_human_0 & formated_M & delta_expected_model \\
formatted_dataset & formatted_pd & S &  &  &  &  &  \\
\midrule
\multirow[t]{4}{*}{MNLI M  $\langle$ GT = 5, L=3 $\rangle$} & 0.40 & 185 & 0.40 & 0.40$\pm$0.06 & 0.004324 & nan & NaN \\
\cline{2-8}
 & 0.60 & 1599 & 0.60 & 0.59$\pm$0.01 & 0.010006 & 0.61 & -0.010000 \\
\cline{2-8}
 & 0.80 & 2457 & 0.80 & 0.80$\pm$0.01 & -0.000814 & 0.78 & 0.020000 \\
\cline{2-8}
 & 1.00 & 5759 & 1.00 & 1.00$\pm$0.00 & 0.000000 & 0.89 & 0.110000 \\
\cline{1-8} \cline{2-8}
\multirow[t]{4}{*}{MNLI MM $\langle$ GT = 5, L=3 $\rangle$} & 0.40 & 168 & 0.40 & 0.39$\pm$0.03 & 0.009524 & nan & NaN \\
\cline{2-8}
 & 0.60 & 1446 & 0.60 & 0.60$\pm$0.01 & -0.002905 & 0.62 & -0.020000 \\
\cline{2-8}
 & 0.80 & 2402 & 0.80 & 0.81$\pm$0.02 & -0.005828 & 0.77 & 0.030000 \\
\cline{2-8}
 & 1.00 & 5984 & 1.00 & 1.00$\pm$0.00 & 0.000000 & 0.90 & 0.100000 \\
\cline{1-8} \cline{2-8}
\bottomrule
\end{tabular}